server:
  port: 6666
  servlet:
    context-path: /miaosha

spring:
  profiles:
    active: dev
  application:
    name: general-miaosha
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    # 数据源使用 TODO 对比不同的主流数据源连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=UTF8
    username: root
    password: root

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml



