server:
  port: 7777
  servlet:
    context-path: /miaosha

spring:
  profiles:
    active: dev
  application:
    name: general-miaosha
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    # 数据源使用 TODO 对比不同的主流数据源连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
#      filter:
#        stat:
#          enabled: true
#        wall:
#          enabled: true
#        slf4j:
#          enabled: true
#      web-stat-filter:
#        enabled: false
#        url-pattern: /*
#        session-stat-enable: true
#        session-stat-max-count: 1000
#      aop-patterns: com.general.miaosha.business.goods.mapper.GoodsMapper
#      stat-view-servlet:
#        enabled: false
#        url-pattern: /druid/*
#        reset-enable: false
#        login-username: admin
#        login-password: admin
#        allow: 127.0.0.1
    url: jdbc:mysql://localhost:3306/miaosha?characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root

mybatis-plus:
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  level:
    com.general.miaosha: info
